FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
COPY . /app/out
WORKDIR /app/out
ENTRYPOINT ["dotnet", "ihs-innerloop.dll"]
ENV PORT=8080
ENV MANAGMENTPORT=8090
ENV ASPNETCORE_URLS="http://0.0.0.0:${PORT};http://0.0.0.0:${MANAGMENTPORT}"
ENV ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
ENV LOGGING__CONSOLE__DISABLECOLORS=true
EXPOSE 8080