apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: net-il
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: net-il
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: net-il
spec:
  source:
    git:
      url: github.com/tezizzm/ihs-innerloop
      ref:
        branch: main
